version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: conventional-commits-parser
    versions:
    - 3.2.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: fs-extra
    versions:
    - 9.0.1
